name: Pull request tests with mocks
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: large_ubuntu_16
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: cp .env.example .env
      - run: pnpm install
      - run: pnpm prettier:check
      - name: pnpm CI test:mock
        run: pnpm test:mock
