name: Pull request tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: large_ubuntu_16
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
      with:
          version: 8
      - run: cp .env.example .env
      - run: pnpm install
      - run: pnpm prettier:check
      - name: "pnpm CI test"
        run: |
          # sometimes not created and is not tailed
          touch fhevm.log
          pnpm fhevm:start &> fhevm.log &
          tail -f fhevm.log | sed '/Starting JSON WebSocket server/ q'
          pnpm fhevm:faucet
          pnpm test
          pnpm fhevm:stop || true